### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sayanee** [sayanee/longform#4]
- [ ]  [Cramming more components onto integrated circuits](https://newsroom.intel.com/wp-content/uploads/sites/11/2018/05/moores-law-electronics.pdf) by Gordon Moore
- [ ] [The Cognitive Style of PowerPoint](https://www.inf.ed.ac.uk/teaching/courses/pi/2016_2017/phil/tufte-powerpoint.pdf) by Edward Tufte 
- [ ] [Supreme Court decision on Google vs Oracle](https://www.supremecourt.gov/opinions/20pdf/18-956_d18f.pdf)
- [ ] [Origin of Covid](https://nicholaswade.medium.com/origin-of-covid-following-the-clues-6f03564c038)
- [ ] [Varieties of Argumentative experience](https://slatestarcodex.com/2018/05/08/varieties-of-argumentative-experience/)
- [ ] [How to report bugs effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)
- [ ] [The Testament of a Furniture Dealer by Ingvar Kamprad](https://www.inter.ikea.com/en/-/media/InterIKEA/IGI/Financial%20Reports/English_The_testament_of_a_dealer_2018.pdf)
- [ ] [Social media and mental health](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3919760)

## ✅  Completed

- [x] [Apple M1 foreshadows Rise of RISC-V](https://erik-engheim.medium.com/apple-m1-foreshadows-risc-v-dd63a62b2562)
- [x] [Beginner's Guide to Arguing Constructively](https://liamrosen.com/arguments.html)
- [x] [Platform Adjacency Theory](https://infrequently.org/2020/06/platform-adjacency-theory/)
- [x] [Why Figma wins](https://kwokchain.com/2020/06/19/why-figma-wins/)
- [x] [Why Is Apple’s M1 Chip So Fast?](https://debugger.medium.com/why-is-apples-m1-chip-so-fast-3262b158cba2)
- [x] [What Does RISC and CISC Mean in 2020?](https://medium.com/swlh/what-does-risc-and-cisc-mean-in-2020-7b4d42c9a9de)
- [x] [IT does not matter by Nick Carr](https://hbr.org/2003/05/it-doesnt-matter)
- [x] [How to ask questions the smart way](http://www.catb.org/~esr/faqs/smart-questions.html)
